openapi: 3.1.0
info:
  title: Verify
  version: '1.0'
  contact:
    name: Engineering
    url: 'https://www.wiresecure.com'
    email: eng@wiresecure.com
servers:
  - url: 'https://api-sandbox.wiresecure.com'
    description: SANDBOX
  - url: 'https://api.wiresecure.com'
    description: PRODUCTION
paths:
  /verify:
    post:
      summary: ''
      operationId: post-verify
      responses:
        '200':
          description: OK
      description: 'Creates a request for wire instructions in the system and returns a URL to be used by the party from whom you are requesting instructions. If instructions are already provided, ID verification will be skipped and the instructions will just need to be confirmed.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                emailAddress:
                  type: string
                phoneNumber:
                  type: string
              required:
                - fullName
                - emailAddress
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    API Key:
      name: API Key
      type: apiKey
      in: header
security:
  - API Key: []
